version: 2

models: 
  - name: orders_fact
    columns:
      - name: order_pk
        tests:
          - not_null
          - unique
      - name: contact_pk
        tests:
          - not_null
  - name: int_companies
    columns:
      - name: company_pk
        tests:
          - not_null
          - unique
  - name: int_contacts
    columns:
      - name: contact_pk
        tests:
          - not_null 
          - unique
  - name: int_orders
    columns:
      - name: order_pk
        tests:
          - not_null
  - name: int_contacts
    columns:
      - name: first_name
        tests:
          - not_null
      - name: last_name
        tests:
          - not_null
