version: 2

sources:
  - name: hubspot
    database: NORTHWINDS
    schema: GET99NVI3S
    tables:
      - name: HUBSPOT_CUSTOMER_DATA
  - name: rds
    database: NORTHWINDS
    schema: NORTHWINDS2_RDS_PUBLIC
    tables:
      - name: orders
      - name: order_details